### ISSUE TITLE
How to specify 'open source only'  scan

### ISSUE THREAD

**Issue by BhavaMada** [hclproducts/appscan-gradle-plugin#14]
I like to run the scan for the **'open source only',**  How do we achieve this using this appscan-gradle-plugin?

**Comment by mattmurp** [comment]
The Gradle plugin does not currently run open source only scans, but it's something we hope to add soon.

**Comment by BhavaMada** [comment]
cool, thanks a lot. I wanted to add all the parameters we set at the appscan-config.xml in this Gradle plugin.
